spring:
  application:
    name: spring
  config:
    import: |
      config/${LOG_CONFIG:default_log}.yml

management:
  endpoint:
    health:
      # http://{host}:{port}/actuator/health ?details??????????????????
      show-details: always
